class UserNotFoundException(Exception):
    pass


class AuthNotValidException(Exception):
    pass
